version: '3.3'

services:
    app:
        build: ./docker/app
        container_name: park_app
        volumes:
            - ./:/var/www/html
        networks:
            - park-network

    nginx:
        container_name: park_nginx
        image: nginx:stable-alpine
        ports:
            - "8082:80"
        volumes:
           - ./:/var/www/html
           - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - park-network

    mysql:
        image: mysql
        container_name: park-db
        restart: unless-stopped
        tty: true
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_USERNAME: ${DB_USERNAME}
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - ./docker/mysql/db:/var/lib/mysql
        networks:
            - park-network

networks:
    park-network:
        driver: bridge