version: '3.3'

services:
    app:
        build:
            context: .
            dockerfile: .docker/app/Dockerfile
        image: 'shouts.dev/laravel'
        container_name: laravel-parking-app
        ports:
            - "8001:80"
        volumes:
            - ./:/var/www/html
        networks:
            - parking-app
        depends_on:
            - mysql
    mysql:
        image: mysql
        container_name: laravel-parking-db
        restart: unless-stopped
        tty: true
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_USERNAME: ${DB_USERNAME}
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - ./.docker/mysql:/var/lib/mysql
        networks:
            - parking-app

networks:
    parking-app:
        driver: bridge